### ISSUE TITLE
新增 -gm/--generate-metadata [directory] 选项，用于在指定目录下生成汇总的元数据与特定目录结构

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#50]
新增 `-gm/--generate-metadata [target_directory]` 选项，用于在指定目录下生成汇总的元数据与特定目录结构。
`target_directory` 可选。如留空默认为 cwd。

对于每一个 `$distro` 在 `$target_directory/$distro_mapped/README.md` 中生成带元信息头的简要、人类易于理解的测试报告（英文优先，i18n 后续实现再考虑），如合适，应附带必要的启动 log、各测试的 log。

`$distro_mapped` 也通过配置文件配置一个映射，保证其目录名与 support-matrix 中使用的目录同步。

元信息头格式如下

```markdown
---
sys: $distro_metaname (通过配置文件的映射与 support-matrix 中使用的名称同步)
sys_ver: null (暂不清楚不指定为 null 是否会影响 support-matrix 中 ci 运行，如不会则可能输出为 uname -a 提取的系统版本号)
sys_var: null

status: basic (如能通过 qemu 启动应该都算 basic 支持不包括图形化, 或者沟通后给一个新状态也可)
last_update: 2024-09-26 (自动化测试日期)
---

..后续防止易于理解的测试报告内容...
```

此外，还需在 $target_directory 中生成一 others.yml。可以直接从配置好的固有文件拷贝内容，或在其上追加自动化测试完全失败（QEMU 环境异常没拉起来）的发行版信息（也许不要追加才会好，如果这次失败了沿用上一次的结果先调试着不要污染支持矩阵结果）。

others.yml 结构类似：

```yaml
- sys: rtthread
  sys_ver: null
  sys_var: null
  status: cft
- sys: openharmony
  sys_ver: null
  sys_var: null
  status: cft
```
